export enum AppContextAction {
	SET_CURRENCY = 'SET_CURRENCY',
	SET_RATES = 'SET_RATES',
	SET_SEARCH_TERM = 'SET_SEARCH_TERM',
	SET_HAS_BACK = 'SET_HAS_BACK',
	SET_TAB_TOP = 'SET_TAB_TOP',
	SET_TAB_SUBSCRIPTIONS = 'SET_TAB_SUBSCRIPTIONS',
}
